### ISSUE TITLE
Not compatible with spring-jdbc-4.2.5?

### ISSUE THREAD

**Issue by denisbetsi** [crate/crate-jdbc#103]
Attempted to use crate jdbc driver with spring jdbc. Getting this error

`
Caused by: java.sql.SQLException: line 1:19: mismatched input 'IF' expecting EOF
	at io.crate.client.jdbc.CrateStatement.execute(CrateStatement.java:72) ~[crate-jdbc-standalone-1.11.0-e943a7f.jar:na]
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:473) ~[spring-jdbc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 62 common frames omitted
Caused by: io.crate.action.sql.SQLActionException: line 1:19: mismatched input 'IF' expecting EOF
	at io.crate.action.sql.TransportBaseSQLAction.buildSQLActionException(TransportBaseSQLAction.java:403) ~[na:na]
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:206) ~[na:na]
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:191) ~[na:na]
	at io.crate.action.sql.TransportBaseSQLAction.doExecute(TransportBaseSQLAction.java:80) ~[na:na]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75) ~[na:na]
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:139) ~[na:na]
	at io.crate.action.sql.TransportSQLAction$TransportHandler.messageReceived(TransportSQLAction.java:127) ~[na:na]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222) ~[na:na]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114) ~[na:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[na:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[na:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[na:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[na:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[na:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[na:na]
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:96) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[na:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[na:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[na:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[na:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[na:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[na:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[na:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[na:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[na:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[na:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
`

Will try to add source vs precompiled library to see what's going on there.

**Comment by mfussenegger** [comment]
This looks like a SQL Parser exception, indicating that a SQL statement that was used isn't supported.
But the Stacktrace doesn't include the complete statement. only that it contains a 'IF'.

You could enable debug logging for `io.crate.action.sql` in order to get more information about the statement that fails

**Comment by denisbetsi** [comment]
I made it work. I've simplified the implementation and it worked.

On separate note, crate-client requires log4j to be properly initialized. Otherwise attempts to debug can lead to weird unrelated errors.

having this 
BasicConfigurator.configure();

is crucial for it to function.

**Comment by denisbetsi** [comment]
Actually never mind, the moment I try to use @Autowire the error comes back. SO I can initialize it manually without any issues.

I dag out the SQL statement it errors out on

DROP TABLE posts IF EXISTS

**Comment by chaudum** [comment]
hi @denisbetsi 
the correct `DROP TABLE` statement is:

```sql
DROP TABLE IF EXISTS posts
```

Did you write the statement on your own, or did some other library/framework create it?

See also our documentation: https://crate.io/docs/reference/sql/reference/drop_table.html

**Comment by denisbetsi** [comment]
Ah I figured it out. It was from schema.sql in the sample. Looks like Spring data was sending HSQLDB from that SQL to Crate jdbc connection instead of HSQLDB. Sorry about the confusion.

**Comment by chaudum** [comment]
no worries @denisbetsi 
thanks for the clarification. we're glad you could solve the issue :)
