### ISSUE TITLE
Crate-JDBC runing on Zeppelin (Spark 2.1.0) Issue

### ISSUE THREAD

**Issue by mvjkumar** [crate/crate-jdbc#228]
Hi,
 I am getting the following exception when running the below code on zepplin (0.7.2) that uses spark interpreter (2.1.0).  Appreciate your quick response

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2, localhost, executor driver): io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: line 1:29: mismatched input 'AS' expecting {'.', 'TO', '='}
```

```java
import org.apache.spark.sql.functions.{concat, lit}
import sqlContext.implicits._
import org.apache.spark.sql.Row
import spark.implicits._
import org.elasticsearch.spark._
import org.elasticsearch.spark.sql._
 
val dbWriteMode = "append"
val dbUrl = "crate://localhost:5433"
val dbDriver = "io.crate.client.jdbc.CrateDriver"
val dbProperties = new java.util.Properties
 
dbProperties.setProperty("driver", dbDriver)
 
val testDF = Seq(
  (1, 5)
).toDF("id", "name")
 
val testWriter = testDF.write.mode(dbWriteMode)
testWriter.jdbc(url=dbUrl, table="test", dbProperties)
```

**Comment by jodok** [comment]
just to be sure - please can you try adding a trailing slash to the dbUrl?
https://crate.io/docs/clients/jdbc/#jdbc-url-format

**Comment by mvjkumar** [comment]
I have done that, i still see the same issue

**Comment by mvjkumar** [comment]
Please find the complete stack trace.. there is an issue when setting the transaction isolation from the spark library


org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 3, localhost, executor driver): io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: line 1:29: mismatched input 'AS' expecting {'.', 'TO', '='}
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:306)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:292)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at io.crate.shade.org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:437)
	at io.crate.shade.org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:844)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:569)
at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:670)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:670)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mvjkumar** [comment]
Hi @jodok - I have found the issue, the spark code is setting the transaction isolation level and the postgres code is trying to run the following query to set the same which is when we are getting the error.
SET SESSION CHARACTERISTICS AS TRANSACTION READ COMMITTED;

I have checked out the code and commented out the code in PGConnection for setTransactionIsolationLevel() and ran my program again and it worked. we need a way to set or skip the transaction isolation level for crate

**Comment by jodok** [comment]
thanks @mvjkumar we also discovered the same :) working on a solution for that!

**Comment by mvjkumar** [comment]
thanks @jodok

**Comment by jodok** [comment]
hey @mvjkumar we've done two things to work around your issue:
- crate can "swallow" the `SET SESSION CHARACTERISTICS` command (https://github.com/crate/crate/commit/603ec1cade24be13e9c6d98c5adec162bc54a035) this is on master / nightly builds and will be released with the next major release (planned ~september).
- if you set the JDBC drivers `strict` parameter to `true` crate will report that it doesn't support transactions and spark won't try to set the transaction isolation level. the fix just has been merged (https://github.com/crate/crate-jdbc/commit/4004a6d2eecc4ecd2b11bc5010588b916174f592) and the 2.2 version of driver will be shortly on bintray.
closing that issue for now. please let us know if this works :)

**Comment by mvjkumar** [comment]
This works, thanks for accommodating this so quick

**Comment by jodok** [comment]
our pleasure :) please let us know if you hit further issues. we're committed to make crate work nice with spark.
