### ISSUE TITLE
Exception: Received resultset tuples, but no field structure for them

### ISSUE THREAD

**Issue by s4s0l** [crate/crate-jdbc#237]
I'm reporting it as jdbc related bug because in server logs all seems fine. I have a unit/integration test that drops schema before each run and from time to time (about 20%) I get this exception, always at the same query. In the same test. I've got many tests and it only happens in this particular test. Every test uses different schema and different tables, what makes this one special is it contains table which is partitioned. 

Below logs from client(crate-jdbc:2.2.0) and from server(2.1.5).

Part of client logs:
```
2017-08-31 01:03:15.992 DEBUG[ScalaTest-run                                ] [s.ConnectionPool$                            ] - Registered connection pool : ConnectionPool(url:jdbc:crate://127.0.0.1:5432/?strict=false, user:) using factory : commons-dbcp2
2017-08-31 01:03:17.356 DEBUG[ScalaTest-run                                ] [s.StatementExecutor$$anon$1                  ] - [SQL Execution] select TABLE_NAME from information_schema.tables where table_schema='betelgeuseakkapersistencejournalcratetest'; (17 ms)
2017-08-31 01:03:17.933 DEBUG[ScalaTest-run                                ] [s.StatementExecutor$$anon$1                  ] - [SQL Execution] drop table betelgeuseakkapersistencejournalcratetest.schema_version; (53 ms)
2017-08-31 01:03:17.959 DEBUG[ScalaTest-run                                ] [s.StatementExecutor$$anon$1                  ] - [SQL Execution] drop table betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity; (20 ms)
2017-08-31 01:03:18.003 ERROR[ScalaTest-run                                ] [s.StatementExecutor$$anon$1                  ] - [SQL Execution Failed] select TABLE_NAME from information_schema.tables where table_schema='locks' and table_name='locks' (Reason: Received resultset tuples, but no field structure for them)
Exception encountered when invoking run on a nested suite - Received resultset tuples, but no field structure for them
java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2089)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeQuery(DBConnectionAttributesWiredPreparedStatement.scala:63)
	at scalikejdbc.StatementExecutor.$anonfun$executeQuery$1(StatementExecutor.scala:337)
```

Crate logs (there is timezone related 2h diff, but its from the same period of time):
```
[2017-08-30T23:01:26,501][INFO ][o.e.c.m.MetaDataCreateIndexService] [Sassolungo di Cibiana] [betelgeuseakkapersistencejournalcratetest.schema_version] creating index, cause [api], templates [crate_defaults], shards [4]/[0], mappings [default]
[2017-08-30T23:01:26,610][INFO ][o.e.c.r.a.AllocationService] [Sassolungo di Cibiana] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[betelgeuseakkapersistencejournalcratetest.schema_version][0]] ...]).
[2017-08-30T23:03:16,240][INFO ][i.c.p.p.SslReqHandler    ] PSQL SSL support is disabled.
[2017-08-30T23:03:17,884][INFO ][o.e.c.m.MetaDataDeleteIndexService] [Sassolungo di Cibiana] [betelgeuseakkapersistencejournalcratetest.schema_version/B4TOBp7qTjSjAK3BJRtd2Q] deleting index

```

**Comment by mfussenegger** [comment]
Thanks for the report.


Would it be possible to 
 - enable `trace` logging in Crate for `io.crate.protocols.postgres` 
 - and `debug` logging in Crate for `io.crate.action.sql` ?

Given that you've already a test-case for this - is it possible for you to extract a minimal reproduction setup from that? The logging output might be enough - but in case this is easy to extract it would help a lot.

**Comment by s4s0l** [comment]
I woke up this morning, and unless im 'sleep coding' I havent changed my code since yesterday, database was not restarted and it stopped happening:/ 

My project is in initial state and is a bit messy - needs a lot of manual setup so it would be waste of your time to set it up, but I've extracted the whole sequence of sqls involved, don't think it will help but maybe later when someone encounters it,this may give some clues.  It was sth like:
```
-- ref:A
CREATE TABLE "betelgeuseakkapersistencejournalcratetest"."schema_version" (
    "installed_rank" INT NOT NULL,
    "version" string,
    "description" string NOT NULL,
    "type" string NOT NULL,
    "script" string NOT NULL,
    "checksum" INTEGER,
    "installed_by" string NOT NULL,
    "installed_on" AS CURRENT_TIMESTAMP,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL,
    primary key (installed_rank)
)
create table betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity (
  tag string  not null,
  id string  not null,
  seq long  not null,
  serialized string not null index off,
  event object,
  json string index off,
  created timestamp generated always as  CURRENT_TIMESTAMP,
  month timestamp GENERATED ALWAYS AS date_trunc('month', CURRENT_TIMESTAMP)
  ,primary key (tag,id,seq,month) --THIS MIGHT HAVE BEEN COMMENTED
) clustered by (tag) into 30 shards PARTITIONED BY (month);
INSERT INTO betelgeuseakkapersistencejournalcratetest.schema_version (
                installed_rank,
                version,
                description,
                type,
                script,
                checksum,
                installed_by,
                execution_time,
                success)
        values (
                1,
                '0.1',
                'crate journal',
                'SQL',
                'V0_1__crate_journal.sql',
                -1112554513,
                'default_user',
                63000,
                'true'
        );
insert into betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity(tag,id,seq,serialized)values('aa','a',1,'sadsadad');
insert into betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity(tag,id,seq,serialized)values('aa1','a1',1,'sadsadad');
insert into betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity(tag,id,seq,serialized)values('aa2','a2',1,'sadsadad');
insert into betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity(tag,id,seq,serialized)values('aa3','a3',1,'sadsadad');
-- ref:B
select TABLE_NAME from information_schema.tables where table_schema='betelgeuseakkapersistencejournalcratetest'
drop table betelgeuseakkapersistencejournalcratetest.crate_async_write_journal_entity;
drop table betelgeuseakkapersistencejournalcratetest.schema_version;
select TABLE_NAME from information_schema.tables where table_schema='locks' and table_name='locks';
``` 
what test did whas sequence ref:B -> ref:A, first time it ran OK, second time failed at last sql of B, so the above sequence should reproduce it, but it does not today.

For now I'd close the issue, I'll back to you if/when it happens again this time with debugging logs hopefully.
