### ISSUE TITLE
Crate-jdbc cannot automatically reconnect crate server

### ISSUE THREAD

**Issue by ghsau** [crate/crate-jdbc#251]
When a node in the cluster is crashed, all JDBC connections are not available, **even if the node is recovered**。My application throws the following exception:
```
Caused by: io.crate.shade.org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:318) ~[crate-jdbc-2.1.7.jar:na]
```
or
```
Caused by: io.crate.shade.org.postgresql.util.PSQLException: This connection has been closed.
        at io.crate.shade.org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:756) ~[crate-jdbc-2.1.7.jar:na]
```
I made the following data source configuration:
```
<property name="testOnBorrow" value="true"/>
<property name="validationInterval" value="5000"/>
<property name="validationQuery" value="SELECT 1"/>
```
When the node is recovered, the JDBC connection is available, **but the JDBC connection is still unavailable during the node crash**. How can I solve this problem?
### Environment
- datasource tomcat-jdbc(8.0.20)
- crate-jdbc 2.17
- crate-server 2.1.8(5 nodes)

Looking forward for your reply, thank you!

**Comment by ghsau** [comment]
I see [this page](https://jdbc.postgresql.org/documentation/head/connect.html#connection-failover)，my jdbc url no problem, but connection cannot fail-over.

**Comment by mxm** [comment]
Thanks for reporting @ghsau!

I'm assuming you have all Crate nodes in your JDBC list? It is normal that the cluster might be temporarily unavailable upon a node crash. When a node fails the cluster has to build a new cluster state and recover data from a lost node.

Could you provide some further information about the tomcat-jgdc configuration, e.g. nodes provided? Have you tried `validationQueryTimeout`?

**Comment by bhagujava** [comment]
@ghsau How did you configured jdbc URL for cratedb ? mine is not working its throw error while connecting to server.

i tried below one

    jdbc:crate://localhost:5434/,localhost:5433/,localhost:5435/demo
 AND 

    crate://localhost:5434/,localhost:5433/,localhost:5435/demo



Exception is : 

````
SQL state [XX000]; error code [0]; ERROR: InvalidRelationName: Relation name ",localhost:5433/,localhost:5435/demo.table1" is invalid.; nested exception is io.crate.shade.org.postgresql.util.PSQLException: ERROR: InvalidRelationName: Relation name ",localhost:5433/,localhost:5435/demo.table1" is invalid.

**Comment by bhagujava** [comment]
It working now. '/' was the issue

    crate://localhost:5434,localhost:5433,localhost:5435/demo




@ghsau  Fail-over is also working fine with driver 2.16


**Environment**
datasource tomcat-jdbc(8.0.20)
crate-jdbc 2.1.6
crate-server latest (3 node)
