### ISSUE TITLE
Errors when DatabaseMetaData getPrimaryKeys 

### ISSUE THREAD

**Issue by BlankRain** [crate/crate-jdbc#255]
Cannot cast constraint_name to type [undefined_table, undefined_set, undefined_array] 
when DatabaseMetaData  getPrimaryKeys
```
io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: Cannot cast constraint_name to type [undefined_table, undefined_set, undefined_array]
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:306)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:292)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at io.crate.shade.org.postgresql.jdbc.PgDatabaseMetaData.getPrimaryKeys(PgDatabaseMetaData.java:1633)
```

Source Code like that:
```

public class App {

  private static List toList(ResultSet rs) throws SQLException {
    List list = new ArrayList();
    ResultSetMetaData md = rs.getMetaData();
    int columnCount = md.getColumnCount();
    while (rs.next()) {
      Map rowData = new HashMap();
      for (int i = 1; i <= columnCount; i++) {
        rowData.put(md.getColumnName(i), rs.getObject(i));
      }
      list.add(rowData);
    }
    return list;
  }

  public static void main(String[] args) {
    try {
      Class.forName("io.crate.client.jdbc.CrateDriver");
     
      Connection con = DriverManager
          .getConnection("jdbc:crate://192.168.31.140:5432/", "crate", null);

      DatabaseMetaData md = con.getMetaData();
      ResultSet tabs = md.getTables(null, null, "hello", null);
      System.out.println(toList(tabs));
      // error start
      ResultSet pks = md.getPrimaryKeys(null, "doc", "hello");
      // error end
      System.out.println(toList(pks));
    } catch (Exception e) {
      e.printStackTrace();
    }

  }
}

```

The Result is 
```
[{TABLE_CAT=doc, TABLE_NAME=hello, SELF_REFERENCING_COL_NAME=_id, TABLE_SCHEM=doc, TYPE_SCHEM=null, TYPE_CAT=null, TABLE_TYPE=BASE TABLE, REMARKS=, REF_GENERATION=SYSTEM, TYPE_NAME=null}]
io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: Cannot cast constraint_name to type [undefined_table, undefined_set, undefined_array]
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:433)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:306)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:292)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at io.crate.shade.org.postgresql.jdbc.PgDatabaseMetaData.getPrimaryKeys(PgDatabaseMetaData.java:1633)
	at aasrnd.App.main(App.java:43)

Process finished with exit code 0
```

the crate jdbc I tested:
```
 <dependency>
      <groupId>io.crate</groupId>
      <artifactId>crate-jdbc-standalone</artifactId>
      <version>2.2.0</version>
    </dependency>

 <dependency>
      <groupId>io.crate</groupId>
      <artifactId>crate-jdbc</artifactId>
      <version>2.2.0</version>
    </dependency>

```

**Comment by mfussenegger** [comment]
Thanks for reporting, we'll take a look at this.

**Comment by BlankRain** [comment]
@chaudum  okay, got it.
