### ISSUE TITLE
Deadlock in PgStatement.killTimerTask

### ISSUE THREAD

**Issue by echarlus** [crate/crate-jdbc#296]
While investigating an issue on my app server (Tomcat8) I traced it down to CrateJDBC driver being in a "deadlocked" state. 
I found the issue by managing to get a full JVM dump and traced it down to this thread : 

> "http-nio-8080-exec-7" #27 daemon prio=5 os_prio=0 tid=0x00007f59805f2800 nid=0xa62 in Object.wait() [0x00007f594c8d2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.killTimerTask(PgStatement.java:935)
	- locked <0x00000000cbfb3920> (a io.crate.shade.org.postgresql.jdbc.PgConnection)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:436)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:359)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at io.crate.shade.org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1332)
	at fr.ocell.ovisuserver.model.DB.getConnection(DB.java:22)

We can see that the Thread is blocked in PgStatement.killTimerTask() method. 
By looking for this specific issue in PGSQL I found this referenced bug : [https://github.com/pgjdbc/pgjdbc/issues/1022](https://github.com/pgjdbc/pgjdbc/issues/1022)
And the fix appears to be included in version 42.2.0 of PGSQL.

By looking at the PGSQL tree currently used by crate-jdbc I've noticed that the fixes referenced by issue mentioned above are not included in current version of crate-jdbc. I believe there has been quite some work done by the PGSQL team regarding this kind of issue and it could be wise to merge them into crate-jdbc. 
Any hope we can all benefit from the latest PGSQL versions ?

**Comment by seut** [comment]
@echarlus On which version of `crate-jdbc` did this deadlock occur? The latest release `2.5.1` of `crate-jdbc` is based on `pgjbc-42.2.5`...

**Comment by echarlus** [comment]
@seut Sorry I forgot to mention version : it's 2.4.0. 
If you say 2.5.1 is based on 42.2.5 then I'll upgrade and see if the problem goes away. That would be great news. I was not able to find reference to PGSQL version in your release notes, where is this located ?

**Comment by echarlus** [comment]
@seut Thanks. I'm upgrading right now and I'll keep you posted if the issue occurs again. 
Thanks for the reactivity !

**Comment by echarlus** [comment]
@seut I got the deadlock again today, even though I've upgraded to 2.5.1 (using crate-jdbc-standalone-2.5.1.jar) 
Here's the log : 
`"http-nio-8080-exec-3" #23 daemon prio=5 os_prio=0 tid=0x00007fc4ec506800 nid=0x4b7d in Object.wait() [0x00007fc49fdfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.killTimerTask(PgStatement.java:984)
    - locked <0x00000000cc2263d8> (a io.crate.shade.org.postgresql.jdbc.PgConnection)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:445)
    at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
    at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:145)
    at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:122)
    at io.crate.shade.org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1412)
    at fr.ocell.ovisuserver.model.DB.getConnection(DB.java:22)
`
This happens when a web requests hits tomcat which spawns a new thread to handle the request. I thy to get a hold of the underlying DB connection and I get stuck (I have a lock to prevent multiple threads opening a connection at the same time). The thread trying to get the DB is suck on the isValid() method of the connection ...

**Comment by basithmsk** [comment]
I am facing a similar deadlock issue with my app server (tomcat 8.5.43) and with postgresql driver version 42.2.2. The issue traced down to the thread :

"Thread-134203"  prio=5 Thread id=315839 TIMED_WAITING|
java.lang.Object.wait(Native Method)|
org.postgresql.jdbc.PgStatement.killTimerTask(PgStatement.java:1011)|
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:451)|
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)|
org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)|
org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)|

As mentioned in the above comments, this seems to be fixed in 42.2.0 version of the driver. I had tested the above scenario with 42.2.12 version of the jar as well and the issue seems to persist. 

Any help on resolving the issue?

**Comment by echarlus** [comment]
@basithmsk I managed to get rid of this issue by using a connexion pool. The JDBC connection is not threadsafe therefore you need to have one connexion per tomcat thread ... The deadlock will occur when two HTTP requests are using the same JDBC connection at the same time.
