### ISSUE TITLE
Unable to initiate connection to cluster

### ISSUE THREAD

**Issue by rookie7799** [crate/crate-jdbc#59]
Calling - DriverManager.getConnection("crate://localhost:4300");

Spits out:

Exception in thread "Thread-20" org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: org.elasticsearch.common.collect.MapBuilder.immutableMap()Lcom/google/common/collect/ImmutableMap;
  at io.crate.client.InternalCrateClient.<init>(Unknown Source)
  while locating io.crate.client.InternalCrateClient

1 error
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at io.crate.client.CrateClient.<init>(CrateClient.java:96)
        at io.crate.client.CrateClient.<init>(CrateClient.java:103)
        at io.crate.client.CrateClient.<init>(CrateClient.java:107)
        at io.crate.client.jdbc.CrateDriver.connect(CrateDriver.java:65)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at jrh.CrateHandler.getPIs(CrateHandler.java:52)
        at jrh.QueryRunner.run(ReportCreator.java:1280)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.elasticsearch.common.collect.MapBuilder.immutableMap()Lcom/google/common/collect/ImmutableMap;
        at io.crate.client.InternalCrateClient.<init>(InternalCrateClient.java:55)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        ... 13 more

**Comment by mfelsche** [comment]
which version of crate-jdbc are you using?

**Comment by rookie7799** [comment]
crate-jdbc-1.5.0.jar
+
guava-15.0.jar

**Comment by mfelsche** [comment]
We are currently preparing a new release which should fix this issue.
Please stay tuned.

**Comment by rookie7799** [comment]
Got it, thank you!

**Comment by mfelsche** [comment]
crate-jdbc 1.5.1 has just been released: https://bintray.com/crate/crate/crate-jdbc/1.5.1/view
this should fix your error.

**Comment by rookie7799** [comment]
Well, that fixed (probably) the original error but now it spits out:

Connecting to crate...
Exception in thread "Thread-83" java.lang.NoClassDefFoundError: io/crate/shade/org/elasticsearch/client/transport/NoNodeAvailableException
        at io.crate.client.jdbc.CrateDriver.connect(CrateDriver.java:59)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at jrh.CrateHandler.getPIs(CrateHandler.java:52)
        at jrh.QueryRunner.run(ReportCreator.java:1280)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.crate.shade.org.elasticsearch.client.transport.NoNodeAvailableException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more

I tried running the query via curl - and it works just fine, so it's not network/firewall issue.

Tried running the code with with elasticsearch-1.3.2.jar and elasticsearch-1.5.0.jar - same outcome.

**Comment by seut** [comment]
can you please provide us a little more information related to your issue?
most interesting:
 - which crate-jdbc jar, standalone one or normal one
 - your java classpath definition
 - the crate server version you're trying to connect to

I've just validate the crate-jdbc jar's and the io/crate/shade/org/elasticsearch/client/transport/NoNodeAvailableException class is available on both.

thanks

**Comment by rookie7799** [comment]
Hello Seut,

- The crate file is crate-jdbc-1.5.1.jar (normal)
- Classpath is not defined, I specify the -cp option at runtime and it points to my project's libs dir
- Crate VERSION: 0.47.8

On a side note, I've had the same issue with CrateClient crate-client-0.47.7.jar and after updating to crate-client-0.47.8.jar - everything started working. So we moved to crate-client instead.

I can continue debugging crate-jdbc if you guys want to figure this out.

thank you!

**Comment by seut** [comment]
Ok so I'll think using the a old crate-client.jar was also the problem with crate-jdbc.
I'll close this now...
